language: php

php:
  - 7.2
  - 7.3
  - 7.4

before_install:
  - composer require "illuminate/support:${ILLUMINATE_VERSION}" --no-update

before_script:
  - composer update --prefer-source --no-interaction

script:
  - vendor/bin/phpunit
